apiVersion: policy.kubernetes.io/v1alpha1
kind: PolicyReport
metadata:
  name: sample-cis-bench-api-server
  labels:
    policy.kubernetes.io/engine: kube-cis
  annotations:
    name: CIS Kubernetes Benchmarks
    category: API Server
    version: v1.5.1 - 02-14-2020
summary:
  pass: 8
  fail: 2
  warn: 0
  info: 0
  error: 0
  skip: 0
results:
  - policy: api-server:anonymous-auth
    message: ensure that --anonymous-auth argument is set to false
    resources:
      - status: Warn
        resource:
          kind: Pod
          Namespace: default
          Name: test
    scored: true
    data:
      category: API Server
      index:  1.2.1


