apiVersion: policy.kubernetes.io/v1alpha1
kind: PolicyReport
metadata:
  name: sample-cis-bench-api-server
  labels:
    policy.kubernetes.io/engine: kube-cis
  annotations:
    name: CIS Kubernetes Benchmarks
    category: API Server
    version: v1.5.1 - 02-14-2020
summary:
  pass: 8
  fail: 2
  warn: 0
  info: 0
  error: 0
  skip: 0
results:
  - policy: api-server:anonymous-auth
    message: ensure that --anonymous-auth argument is set to false
    status: Warn
    scored: true
    data:
      category: API Server
      index:  1.2.1
  - policy: api-server:basic-auth-file
    message: ensure that --basic-auth-file argument is not set
    status: Fail
    scored: true
    data:
      category: API Server
      index:  1.2.2
  - policy: api-server:token-auth-file
    message: ensure that --token-auth-file argument is not set
    status: Warn
    scored: false
    data:
      category: API Server
      index:  1.2.2

